FROM ubuntu:14.04
MAINTAINER yamamuteki <yama@muteki.com>

ENV ORMASTER_PASSWORD=ormaster
#PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Reference to http://www.orca.med.or.jp/receipt/download/trusty/trusty_install_48.html.
RUN set -xe \
# wgetをインストール
　

EXPOSE 8000
CMD service postgresql restart && service jma-receipt start && tail -f /dev/null
